#	brent's quick'n'dirty voltage divider calculator
vs = float(input("Voltage Source (V)= "))
r1 = float(input("Resistor 1 (ohms)= "))
r2 = float(input("Resistor 2 (ohms)= "))
vout = (vs*r2)/(r1+r2)
print("{} {} V".format("VOUT=", vout))
print("{}V ={} ".format(vs,"Vin----------"))
print("		  |")
print("		 _______________")
print("{}{} ohm|".format("		|R1 = ", r1))
print("		 ---------------")
print("		  |")
print("{} {}V".format("		  *---Vout = ", vout))
print("		  |")
print("		 _______________")
print("{}{} ohm|".format("		|R2 = ", r2))
print("		 ---------------")
print("		  |")
print("		  |")
print("		 GND")
